
services:

  app:
    image: app-db-kits
    # container_name: my-spring-app
    ports:
      - "8080:8080"
    #  - "9090:9090" # Spring Actuator
    volumes:
      - ./config/:/app/config/
    environment:
    #  - SPRING_PROFILES_ACTIVE=prod
      - SPRING_PROFILES_ACTIVE=test
    #  - SPRING_CONFIG_LOCATION=file:/app/config/
    restart: unless-stopped

  mysql:
    # container_name: some-mysql
    hostname: mysql-db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=devtest
      - MYSQL_USER=devtest
      - MYSQL_PASSWORD=devtest123456
    image: mysql:lts
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql-data/db:/var/lib/mysql
    #ports:
    #  - 3306:3306/tcp

  mongo:
    hostname: mongo-db
    image: mongo
    restart: unless-stopped
    volumes:
      - ./mongo-data/db:/data/db
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
